[workspace]

members = [
    "getting-started/cli/",
    "getting-started/output/",
    "getting-started/loader/",
    "getting-started/ctf/",
    "getting-started/logging",
    "getting-started/automated_testing"
]