[package]
name = "binary1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.19"
env_logger = "0.10.0"
anyhow = "1.0.72"

[dev-dependencies]
rand = "0.8.5"