[package]
name = "block-transition-validation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = {version = "4.0", features = ["derive"]}
fuel-core = {version = "0.20.1", features = ["relayer"]}
fuel-core-storage = "0.20.1"
fuels=  "0.44.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
log = "0.4.19"
env_logger = "0.10.0"